server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reservio
    username: admin
    password: reservio
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        id:
          new_generator_mappings: true
    jackson:
      serialization:
        fail-on-empty-beans: false
    sql:
      init:
        mode: always